import type { MockRunManifest } from "./types.js";

export const TODO_BASELINE_FILES: Record<string, string> = {
  ".gitignore": [
    "# Beads / Dolt files (added by bd init)",
    ".dolt/",
    "*.db",
    ".beads-credential-key",
    ".aegis/config.json",
    ".aegis/dispatch-state.json",
    ".aegis/merge-queue.json",
    ".aegis/mnemosyne.jsonl",
    ".aegis/runtime-state.json",
    ".aegis/labors/",
    ".aegis/evals/",
    ".aegis/mock-run-manifest.json",
    ".aegis/oracle/",
  ].join("\n"),
  ".pi/settings.json": JSON.stringify(
    {
      defaultProvider: "google",
      defaultModel: "gemma-4-31b-it",
      defaultThinkingLevel: "high",
    },
    null,
    2,
  ),
};

export const TODO_MOCK_RUN_ISSUES: MockRunManifest["issues"] = [
  {
    key: "todo-system",
    title: "Todo system program",
    description: "Program epic for the deterministic mock-run todo system.",
    issueType: "epic",
    priority: 1,
    queueRole: "coordination",
    parentKey: null,
    blocks: [],
    labels: ["mock-run", "program"],
  },
  {
    key: "foundation",
    title: "Foundation slice",
    description: "Coordination epic for foundation work.",
    issueType: "epic",
    priority: 1,
    queueRole: "coordination",
    parentKey: "todo-system",
    blocks: [],
    labels: ["mock-run", "slice", "foundation"],
  },
  {
    key: "foundation.contract",
    title: "[foundation] Contract seed",
    description: "Lock the todo model, storage interface, and baseline test contract.",
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "foundation",
    blocks: [],
    labels: ["mock-run", "foundation", "contract"],
  },
  {
    key: "foundation.lane_a",
    title: "[foundation] Lane A",
    description: "Implement task model and in-memory store behavior.",
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "foundation",
    blocks: ["foundation.contract"],
    labels: ["mock-run", "foundation", "lane_a"],
  },
  {
    key: "foundation.lane_b",
    title: "[foundation] Lane B",
    description: "Implement shared validation and baseline test utilities.",
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "foundation",
    blocks: ["foundation.contract"],
    labels: ["mock-run", "foundation", "lane_b"],
  },
  {
    key: "foundation.gate",
    title: "[foundation] Gate",
    description: "Prove the foundation slice and unlock commands.",
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "foundation",
    blocks: ["foundation.lane_a", "foundation.lane_b"],
    labels: ["mock-run", "foundation", "gate"],
  },
  {
    key: "commands",
    title: "Commands slice",
    description: "Coordination epic for command work.",
    issueType: "epic",
    priority: 1,
    queueRole: "coordination",
    parentKey: "todo-system",
    blocks: [],
    labels: ["mock-run", "slice", "commands"],
  },
  {
    key: "commands.contract",
    title: "[commands] Contract seed",
    description: "Define command behavior for create, list, and complete flows.",
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "commands",
    blocks: ["foundation.gate"],
    labels: ["mock-run", "commands", "contract"],
  },
  {
    key: "commands.lane_a",
    title: "[commands] Lane A",
    description: "Implement create and list commands.",
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "commands",
    blocks: ["commands.contract"],
    labels: ["mock-run", "commands", "lane_a"],
  },
  {
    key: "commands.lane_b",
    title: "[commands] Lane B",
    description: "Implement complete-task behavior and command tests.",
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "commands",
    blocks: ["commands.contract"],
    labels: ["mock-run", "commands", "lane_b"],
  },
  {
    key: "commands.gate",
    title: "[commands] Gate",
    description: "Prove the command slice and unlock integration.",
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "commands",
    blocks: ["commands.lane_a", "commands.lane_b"],
    labels: ["mock-run", "commands", "gate"],
  },
  {
    key: "integration",
    title: "Integration slice",
    description: "Coordination epic for CLI and reporting work.",
    issueType: "epic",
    priority: 1,
    queueRole: "coordination",
    parentKey: "todo-system",
    blocks: [],
    labels: ["mock-run", "slice", "integration"],
  },
  {
    key: "integration.contract",
    title: "[integration] Contract seed",
    description: "Lock CLI integration, summary output, and end-to-end behavior.",
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "integration",
    blocks: ["commands.gate"],
    labels: ["mock-run", "integration", "contract"],
  },
  {
    key: "integration.lane_a",
    title: "[integration] Lane A",
    description: "Implement CLI wiring.",
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "integration",
    blocks: ["integration.contract"],
    labels: ["mock-run", "integration", "lane_a"],
  },
  {
    key: "integration.lane_b",
    title: "[integration] Lane B",
    description: "Implement reporting and end-to-end verification.",
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "integration",
    blocks: ["integration.contract"],
    labels: ["mock-run", "integration", "lane_b"],
  },
  {
    key: "integration.gate",
    title: "[integration] Gate",
    description: "Prove the integrated todo system.",
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "integration",
    blocks: ["integration.lane_a", "integration.lane_b"],
    labels: ["mock-run", "integration", "gate"],
  },
];

export const TODO_READY_QUEUE_EXPECTATION = ["foundation.contract"] as const;

export const TODO_MOCK_RUN_MANIFEST: MockRunManifest = {
  repoName: "aegis-mock-run",
  beadsPrefix: "aegismockrun",
  baselineFiles: TODO_BASELINE_FILES,
  issues: TODO_MOCK_RUN_ISSUES,
  expectedInitialReadyKeys: [...TODO_READY_QUEUE_EXPECTATION],
};
