import type { MockRunManifest } from "./types.js";

export const TODO_MOCK_RUN_ISSUES: MockRunManifest["issues"] = [
  {
    key: "todo-webapp.program",
    title: "Fancy animated React todo webapp program",
    description: "Program epic for building a localhost React animated todo application from an empty repository.",
    issueType: "epic",
    priority: 1,
    queueRole: "coordination",
    parentKey: null,
    blocks: [],
    labels: ["mock-run", "program", "react", "todo"],
  },
  {
    key: "setup",
    title: "Setup slice",
    description: "Coordination epic for workspace bootstrap, toolchain, and deterministic starter contract.",
    issueType: "epic",
    priority: 1,
    queueRole: "coordination",
    parentKey: "todo-webapp.program",
    blocks: [],
    labels: ["mock-run", "slice", "setup"],
  },
  {
    key: "setup.contract",
    title: "[setup] Contract seed",
    description: "Lock architecture contract for empty repo -> React app scaffolding, dependency install, and local run targets.",
    fileScope: ["docs/setup-contract.md"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "setup",
    blocks: [],
    labels: ["mock-run", "setup", "contract"],
  },
  {
    key: "setup.dependencies",
    title: "[setup] Install core dependencies",
    description: [
      "Install React runtime, Vite/TypeScript toolchain, animation libs, UI utility packages, and deterministic dev/build/preview npm scripts.",
      "Do not require build or preview checks to pass in this lane; scaffold and tooling lanes own those files.",
      "Do not create blockers for scaffold or tooling files already represented by downstream seeded setup issues.",
    ].join("\n"),
    fileScope: ["package.json", "package-lock.json"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "setup",
    blocks: ["setup.contract"],
    labels: ["mock-run", "setup", "lane_b", "deps"],
  },
  {
    key: "setup.scaffold",
    title: "[setup] Scaffold app shell",
    description: "Scaffold React + TypeScript localhost app shell and baseline source tree.",
    fileScope: [
      "index.html",
      "public/favicon.ico",
      "src/main.tsx",
      "src/App.tsx",
      "src/App.css",
      "src/index.css",
      "src/vite-env.d.ts",
    ],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "setup",
    blocks: ["setup.dependencies"],
    labels: ["mock-run", "setup", "lane_a", "scaffold"],
  },
  {
    key: "setup.tooling",
    title: "[setup] Wire tooling",
    description: "Configure linting, formatting, and test runner scripts for repeatable local development.",
    fileScope: [
      ".eslintrc.json",
      ".prettierrc",
      "package-lock.json",
      "package.json",
      "tsconfig.json",
      "tsconfig.node.json",
      "vite.config.ts",
    ],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "setup",
    blocks: ["setup.scaffold"],
    labels: ["mock-run", "setup", "lane_c", "tooling"],
  },
  {
    key: "setup.gate",
    title: "[setup] Gate",
    description: "Validate scaffold, deps, and tooling completion before feature implementation begins.",
    fileScope: ["docs/setup-gate.md"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "setup",
    blocks: ["setup.scaffold", "setup.dependencies", "setup.tooling"],
    labels: ["mock-run", "setup", "gate"],
  },
  {
    key: "core",
    title: "Core logic slice",
    description: "Coordination epic for todo domain model, state management, and command behavior.",
    issueType: "epic",
    priority: 1,
    queueRole: "coordination",
    parentKey: "todo-webapp.program",
    blocks: [],
    labels: ["mock-run", "slice", "core"],
  },
  {
    key: "core.contract",
    title: "[core] Contract seed",
    description: "Define todo model, persistence contract, and command semantics for create/toggle/delete flows.",
    fileScope: ["docs/core-contract.md"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "core",
    blocks: ["setup.gate"],
    labels: ["mock-run", "core", "contract"],
  },
  {
    key: "core.model",
    title: "[core] Lane A",
    description: "Implement todo entities, validation helpers, and deterministic ids/timestamps.",
    fileScope: ["src/domain/todo.ts"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "core",
    blocks: ["core.contract"],
    labels: ["mock-run", "core", "lane_a"],
  },
  {
    key: "core.state",
    title: "[core] Lane B",
    description: "Implement app state store with local persistence and selectors for filtered views.",
    fileScope: ["src/state/todo-store.ts"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "core",
    blocks: ["core.contract"],
    labels: ["mock-run", "core", "lane_b"],
  },
  {
    key: "core.commands",
    title: "[core] Lane C",
    description: "Implement create/toggle/delete/clear-completed commands with unit tests.",
    fileScope: ["src/state/todo-commands.ts", "src/state/todo-commands.test.ts"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "core",
    blocks: ["core.contract"],
    labels: ["mock-run", "core", "lane_c"],
  },
  {
    key: "core.gate",
    title: "[core] Gate",
    description: "Prove core model/state/commands lanes and unlock UI implementation.",
    fileScope: ["docs/core-gate.md"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "core",
    blocks: ["core.model", "core.state", "core.commands"],
    labels: ["mock-run", "core", "gate"],
  },
  {
    key: "ui",
    title: "UI slice",
    description: "Coordination epic for React components, layout, and interaction shell.",
    issueType: "epic",
    priority: 1,
    queueRole: "coordination",
    parentKey: "todo-webapp.program",
    blocks: [],
    labels: ["mock-run", "slice", "ui"],
  },
  {
    key: "ui.contract",
    title: "[ui] Contract seed",
    description: "Define component boundaries and interaction contract for todo entry, list, filters, and counters.",
    fileScope: ["docs/ui-contract.md"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "ui",
    blocks: ["core.gate"],
    labels: ["mock-run", "ui", "contract"],
  },
  {
    key: "ui.layout",
    title: "[ui] Lane A",
    description: "Build app shell layout, responsive container, and semantic landmark structure.",
    fileScope: [
      "src/App.tsx",
      "src/components/AppShell.tsx",
      "src/components/AppShell.css",
    ],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "ui",
    blocks: ["ui.contract"],
    labels: ["mock-run", "ui", "lane_a"],
  },
  {
    key: "ui.components",
    title: "[ui] Lane B",
    description: "Implement todo list/item and input/filter components bound to core store commands.",
    fileScope: [
      "src/components/TodoInput.tsx",
      "src/components/TodoList.tsx",
      "src/components/TodoItem.tsx",
      "src/components/TodoFilters.tsx",
    ],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "ui",
    blocks: ["ui.contract"],
    labels: ["mock-run", "ui", "lane_b"],
  },
  {
    key: "ui.accessibility",
    title: "[ui] Lane C",
    description: "Add keyboard affordances, focus states, aria annotations, and screen-reader labels.",
    fileScope: ["src/components/A11yStatus.tsx", "src/accessibility/keyboard.ts"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "ui",
    blocks: ["ui.contract"],
    labels: ["mock-run", "ui", "lane_c", "a11y"],
  },
  {
    key: "ui.gate",
    title: "[ui] Gate",
    description: "Prove UI structure, component behavior, and accessibility before motion polish.",
    fileScope: ["docs/ui-gate.md"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "ui",
    blocks: ["ui.layout", "ui.components", "ui.accessibility"],
    labels: ["mock-run", "ui", "gate"],
  },
  {
    key: "motion",
    title: "Motion and polish slice",
    description: "Coordination epic for fancy animations, visual system, and interaction polish.",
    issueType: "epic",
    priority: 1,
    queueRole: "coordination",
    parentKey: "todo-webapp.program",
    blocks: [],
    labels: ["mock-run", "slice", "motion"],
  },
  {
    key: "motion.contract",
    title: "[motion] Contract seed",
    description: "Define animation choreography, reduced-motion fallback, and visual polish acceptance criteria.",
    fileScope: ["docs/motion-contract.md"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "motion",
    blocks: ["ui.gate"],
    labels: ["mock-run", "motion", "contract"],
  },
  {
    key: "motion.item-animations",
    title: "[motion] Lane A",
    description: "Implement animated entry/exit/complete transitions for todo items.",
    fileScope: ["src/motion/itemMotion.ts", "src/components/AnimatedTodoItem.tsx"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "motion",
    blocks: ["motion.contract"],
    labels: ["mock-run", "motion", "lane_a"],
  },
  {
    key: "motion.reorder-feedback",
    title: "[motion] Lane B",
    description: "Implement reorder drag feedback and smooth list reflow motion.",
    fileScope: ["src/motion/reorderMotion.ts", "src/components/ReorderFeedback.tsx"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "motion",
    blocks: ["motion.contract"],
    labels: ["mock-run", "motion", "lane_b"],
  },
  {
    key: "motion.visual-theme",
    title: "[motion] Lane C",
    description: "Implement themed gradients, shadows, and typography polish for fancy localhost presentation.",
    fileScope: ["src/styles/theme.css", "src/styles/theme.ts"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "motion",
    blocks: ["motion.contract"],
    labels: ["mock-run", "motion", "lane_c"],
  },
  {
    key: "motion.gate",
    title: "[motion] Gate",
    description: "Prove animation and polish lanes are complete and stable.",
    fileScope: ["docs/motion-gate.md"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "motion",
    blocks: ["motion.item-animations", "motion.reorder-feedback", "motion.visual-theme"],
    labels: ["mock-run", "motion", "gate"],
  },
  {
    key: "release",
    title: "Release slice",
    description: "Coordination epic for localhost run readiness, docs, and final acceptance proof.",
    issueType: "epic",
    priority: 1,
    queueRole: "coordination",
    parentKey: "todo-webapp.program",
    blocks: [],
    labels: ["mock-run", "slice", "release"],
  },
  {
    key: "release.contract",
    title: "[release] Contract seed",
    description: "Define done criteria for finished localhost app including run command, build check, and smoke steps.",
    fileScope: ["docs/release-contract.md"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "release",
    blocks: ["motion.gate"],
    labels: ["mock-run", "release", "contract"],
  },
  {
    key: "release.localhost",
    title: "[release] Lane A",
    description: "Wire deterministic localhost run flow and production build validation commands.",
    fileScope: ["package.json", "vite.config.ts"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "release",
    blocks: ["release.contract"],
    labels: ["mock-run", "release", "lane_a"],
  },
  {
    key: "release.verification",
    title: "[release] Lane B",
    description: "Add integration smoke checks proving todo flows and animation fallbacks under local run.",
    fileScope: ["tests/smoke/todo-flow.test.ts", "tests/smoke/reduced-motion.test.ts"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "release",
    blocks: ["release.contract"],
    labels: ["mock-run", "release", "lane_b"],
  },
  {
    key: "release.docs",
    title: "[release] Lane C",
    description: "Write concise README runbook documenting setup, commands, and localhost app behavior.",
    fileScope: ["README.md"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "release",
    blocks: ["release.contract"],
    labels: ["mock-run", "release", "lane_c"],
  },
  {
    key: "release.gate",
    title: "[release] Gate",
    description: "Final proof gate: localhost app finished, documented, and reproducibly runnable.",
    fileScope: ["docs/release-gate.md"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "release",
    blocks: ["release.localhost", "release.verification", "release.docs"],
    labels: ["mock-run", "release", "gate"],
  },
];

export const TODO_READY_QUEUE_EXPECTATION = ["setup.contract"] as const;

export const TODO_MOCK_RUN_MANIFEST: MockRunManifest = {
  repoName: "aegis-mock-run",
  beadsPrefix: "aegismockrun",
  issues: TODO_MOCK_RUN_ISSUES,
  expectedInitialReadyKeys: [...TODO_READY_QUEUE_EXPECTATION],
};
